version: 2

models:
  - name: my_first_dbt_model
    description: "Customer-level order summary built from BigQuery public ecommerce data."
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

      - name: total_orders
        tests:
          - not_null

      - name: total_spend
        tests:
          - not_null